"""add column

Revision ID: 50f6740a88c2
Revises: db336b050eaa
Create Date: 2024-07-15 16:57:16.336029

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50f6740a88c2"
down_revision: Union[str, None] = "db336b050eaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_email", sa.Column("age", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_email", "age")
    # ### end Alembic commands ###
