"""upgrade schema v3

Revision ID: 8686e284dfba
Revises: e246446ad5eb
Create Date: 2024-08-03 17:22:00.244136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8686e284dfba'
down_revision: Union[str, None] = 'e246446ad5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_file', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_file', 'updated_at')
    # ### end Alembic commands ###
