"""upgrade schema v2

Revision ID: e246446ad5eb
Revises: 60298d0e3d60
Create Date: 2024-08-02 21:31:10.443506

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e246446ad5eb'
down_revision: Union[str, None] = '60298d0e3d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_survey', sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.add_column('enterprise_survey', sa.Column('file_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_enterprise_survey_file_id_uploaded_file'), 'enterprise_survey', 'uploaded_file', ['file_id'], ['id'])
    op.add_column('geo', sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.add_column('geo', sa.Column('file_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_geo_file_id_uploaded_file'), 'geo', 'uploaded_file', ['file_id'], ['id'])
    op.add_column('user_ls_phone', sa.Column('file_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_user_ls_phone_file_id_uploaded_file'), 'user_ls_phone', 'uploaded_file', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_ls_phone_file_id_uploaded_file'), 'user_ls_phone', type_='foreignkey')
    op.drop_column('user_ls_phone', 'file_id')
    op.drop_constraint(op.f('fk_geo_file_id_uploaded_file'), 'geo', type_='foreignkey')
    op.drop_column('geo', 'file_id')
    op.drop_column('geo', 'id')
    op.drop_constraint(op.f('fk_enterprise_survey_file_id_uploaded_file'), 'enterprise_survey', type_='foreignkey')
    op.drop_column('enterprise_survey', 'file_id')
    op.drop_column('enterprise_survey', 'id')
    # ### end Alembic commands ###
