"""init

Revision ID: 959fb038e3d4
Revises:
Create Date: 2024-07-16 11:57:49.686378

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "959fb038e3d4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_ls_phone",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("ls", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_ls_phone")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_ls_phone")
    # ### end Alembic commands ###
