"""upgrade schema

Revision ID: 60298d0e3d60
Revises: d57ba2227962
Create Date: 2024-08-02 21:09:51.938675

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '60298d0e3d60'
down_revision: Union[str, None] = 'd57ba2227962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_file',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("date_trunc('second', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_file'))
    )
    op.drop_column('user_ls_phone', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ls_phone', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table('uploaded_file')
    # ### end Alembic commands ###
