"""add table

Revision ID: 4e6a7c537423
Revises: 959fb038e3d4
Create Date: 2024-07-29 14:04:17.969623

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e6a7c537423"
down_revision: Union[str, None] = "959fb038e3d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enterprise_survey",
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("industry_aggregation_nzsioc", sa.String(), nullable=True),
        sa.Column("industry_code_nzsioc", sa.String(), nullable=True),
        sa.Column("industry_name_nzsioc", sa.String(), nullable=True),
        sa.Column("units", sa.String(), nullable=True),
        sa.Column("variable_code", sa.String(), nullable=True),
        sa.Column("variable_name", sa.String(), nullable=True),
        sa.Column("variable_category", sa.String(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enterprise_survey")
    # ### end Alembic commands ###
